---
# Tap.
- name: Ensure configured taps are tapped.
  homebrew_tap:
    tap: '{{ item.name | default(item) }}'
    url: '{{ item.url | default(omit) }}'
    state: present
  loop: "{{ homebrew_taps }}"
  tags: brew

# Cask.
- name: Ensure blacklisted cask applications are not installed.
  homebrew_cask: "name={{ item }} state=absent"
  loop: "{{ homebrew_cask_uninstalled_apps }}"
  tags: brew

- name: Install configured cask applications.
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default(omit) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop: "{{ homebrew_cask_apps }}"
  tags: brew

# Brew.
- name: Ensure blacklisted homebrew packages are not installed.
  homebrew: "name={{ item }} state=absent"
  loop: "{{ homebrew_uninstalled_packages }}"
  tags: brew

- name: Ensure configured homebrew packages are installed.
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_installed_packages }}"
  tags: brew

- name: Upgrade all homebrew packages (if configured).
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade_all_packages
  tags: brew
