---
- name: "See if Dock item {{ item.name | default(item) }} exists."
  ansible.builtin.command: "dockutil --find '{{ item.name }}'"
  register: dockitem_exists
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  changed_when: false
  loop: "{{ dockitems_persist }}"
  tags: ['dock']

- name: Ensure Dock item {{ item.item.name | default(item.item.name) }} exists.
  ansible.builtin.command: "dockutil --add '{{ item.item.path }}' --no-restart"
  when: 'item.rc > 0'
  loop: "{{ dockitem_exists.results  }}"
  tags: ['dock']
  notify: 'Restart Dock'

