---
- name: create ssh keys folder
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0755'

- name: write to file
  ansible.builtin.copy:
    content: "{{ item.base64_content | b64decode }}"
    dest: "~/.ssh/{{ item.file_name }}"
    mode: '0600'
  loop: "{{ ssh_private_keys }}"