---
- name: Install visual studio code extensions
  shell: "code --install-extension {{ item }}"
  with_items:
    - Shan.code-settings-sync

- name: Add custom settings for VS Code.
  template:
    src: templates/vs_settings.json.j2
    dest: "~/Library/Application Support/Code/User/settings.json"
