---
- name: "See if {{ item }} is in the Dock."
  ansible.builtin.command:
    cmd: dockutil --find '{{ item }}'
  register: dockitem_exists
  changed_when: false
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  loop: "{{ dockitems_remove }}"
  tags: ['dock']

- name: Ensure Dock item {{ item }} is removed.
  ansible.builtin.command:
    cmd: dockutil --remove '{{ item }} --no-restart'
  loop: "{{ dockitems_remove }}"
  ignore_errors: yes
  tags: ['dock']
  notify: 'Restart Dock'